# Generated by Django 2.2.7 on 2021-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMovemnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_movement', models.CharField(help_text='example; Your item left qater wherehouse', max_length=100)),
                ('second_movement', models.CharField(help_text='example; Your item arrived poland wherehouse', max_length=100)),
                ('third_movement', models.CharField(help_text='example; Your item left lagos wherehouse', max_length=100)),
                ('fourth_movement', models.CharField(help_text='example; Your item arrived spain wherehouse', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(help_text='This is the area for the delivery address', max_length=100)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('pending', 'pending'), ('active', 'active'), ('delayed', 'delayed')], default=1, help_text='This section shows the client the status of their item', max_length=11)),
                ('tracking_number', models.CharField(help_text='This is the tracking number you give to your client.', max_length=20)),
                ('content', models.TextField(help_text='This is where you the gift(s) for your client.', max_length=100)),
                ('delivery_day', models.CharField(help_text='this data will be displayed as" your package will be deliverd on or before the number you enter here"', max_length=5)),
            ],
        ),
    ]
