# Generated by Django 2.2.7 on 2021-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_auto_20210427_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetail',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('delivered', 'delivered'), ('delayed', 'delayed')], default=1, help_text='This section shows the client the status of their item', max_length=11),
        ),
    ]
